name: Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
          
      - name: Connect to remote server and run command
        run: |
          ssh-keyscan "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts
          ssh "${{ secrets.APP_USER }}"@"${{ secrets.SERVER_IP }}" "cd /home/admin/public_html && git reset --hard master && git pull origin master && npm install --force && npm run build"
